version: '2'
services:
  sqli-union:
    build: ./sqli/union
    ports:
     - "5000:5000"

  sqli-error:
    build: ./sqli/error
    ports:
     - "5001:5000"

  sqli-blind:
    build: ./sqli/blind
    ports:
     - "5002:5000"

  template-inj:
    build: ./template_inj
    ports:
     - "5003:5000"

  xss:
    build: ./xss/xss-board
    ports:
     - "5004:80"
